commitChanges async api
Snapchat/KeyDB pull request #727
Opened 2023-10-24 18:59 UTC by AnkitaSuman07

Hi John, This MR is for thorough review . The above changes is causing deadlock issue, also block clients is not  handled properly for async endwritebatch i.e begin_endwritebatch. 
Please suggest possible improvements to make this code working.

2023-10-26 17:55 UTC, AnkitaSuman07 commented
Attaching logs file for deadlock issues observed. 
[448_endWriteBatch_async_crash.txt](https://github.com/Snapchat/KeyDB/files/13181016/448_endWriteBatch_async_crash.txt)
[logs_2.txt](https://github.com/Snapchat/KeyDB/files/13181017/logs_2.txt)

2023-10-27 18:57 UTC, AnkitaSuman07 commented on src/storage/rocksdb.cpp
> +        tspdb.reset();
remove this

2023-10-27 19:15 UTC, AnkitaSuman07 commented on src/storage/rocksdb.cpp
> +    rocksdb::WriteBatch* tspbatch;
naming convention , make it unique_ptr and transfer ownership and release lock in complete

2023-10-30 21:42 UTC, yzhao244 commented
@paulmchen @JohnSully Hi John, here is the PR for the async commit which we went over last Friday.  Please help review when you get a chance.  @AnkitaSuman07 For the issue you are facing today,  please share more details in this PR with John.

2023-10-31 03:28 UTC, AnkitaSuman07 commented
> @paulmchen @JohnSully Hi John, here is the PR for the async commit which we went over last Friday. Please help review when you get a chance. @AnkitaSuman07 For the issue you are facing today, please share more details in this PR with John.

Hi John,  I observed the AePostFunction callback function is not processed and waits forever. There was no keydb crash observed but there is this never ending wait in the task queue. 
23639:23872:M 31 Oct 2023 02:51:33.952 # redisDbPersistentData::processStorageToken
23639:23872:M 31 Oct 2023 02:51:33.952 # RocksEncoderStorageProvider::beginWriteBatch
23639:23872:M 31 Oct 2023 02:51:33.952 # RocksEncoderStorageProvider::begin_endWriteBatch
23639:23873:M 31 Oct 2023 02:51:33.952 # redisDbPersistentData::processStorageToken
23639:23872:M 31 Oct 2023 02:51:33.952 # Populating token objects
23639:23873:M 31 Oct 2023 02:51:33.953 # RocksEncoderStorageProvider::beginWriteBatch
23639:23873:M 31 Oct 2023 02:51:33.953 # RocksEncoderStorageProvider::begin_endWriteBatch
23639:23873:M 31 Oct 2023 02:51:33.953 # Populating token objects
23639:23874:M 31 Oct 2023 02:51:33.990 # redisDbPersistentData::processStorageToken
23639:23874:M 31 Oct 2023 02:51:33.991 # redisDbPersistentData::processStorageToken
23639:23874:M 31 Oct 2023 02:51:33.991 # RocksEncoderStorageProvider::beginWriteBatch
23639:23874:M 31 Oct 2023 02:51:33.991 # RocksEncoderStorageProvider::begin_endWriteBatch
23639:23874:M 31 Oct 2023 02:51:33.991 # Populating token objects
23639:23871:M 31 Oct 2023 02:51:33.991 # redisDbPersistentData::processStorageToken
23639:23871:M 31 Oct 2023 02:51:33.992 # RocksEncoderStorageProvider::beginWriteBatch
23639:23871:M 31 Oct 2023 02:51:33.992 # RocksEncoderStorageProvider::begin_endWriteBatch
23639:23871:M 31 Oct 2023 02:51:33.992 # Populating token objects
23639:23873:M 31 Oct 2023 02:51:34.081 # redisDbPersistentData::processStorageToken
23639:23873:M 31 Oct 2023 02:51:34.081 # RocksEncoderStorageProvider::beginWriteBatch
23639:23873:M 31 Oct 2023 02:51:34.081 # RocksEncoderStorageProvider::begin_endWriteBatch
23639:23873:M 31 Oct 2023 02:51:34.081 # Populating token objects

![image](https://github.com/Snapchat/KeyDB/assets/27730686/af29b5ee-b694-4264-811d-56a400d10000)

Please let me know if you can see anything is not correct

2023-10-31 11:14 UTC, paulmchen commented
@JohnSully John, could you please take a look at this PR and see if the change makes sense. Thank you.

2023-11-03 22:20 UTC, yzhao244 commented
1. What problem i have when applying this commit
   memtier got stuck in the middle, and it seems threads are hanging somewhere in the code logic so that either building a new redis-cli command or run a redis cli command is not possible, redis cli commands just got stuck 
   
2. How i can reproduce it
   **When running the following memtiers on client machine, the memtier process may get stuck at a couple of percent or more and please note that this issue is not reproducible consistently because sometimes the same memtier script was able to finish the whole run.** 
   ./memtier_benchmark -s 172.25.0.89 -p 8000 -t 8 -c 50 -n allkeys -d 32 --random-data --randomize --key-minimum=1 --key-maximum=6000000 --ratio 1:0 --key-pattern=P:P --hide-histogram --cluster-mode   
   ./memtier_benchmark -s 172.25.0.89  -p 8000 -c 2500 -t 4 -n 15000 --random-data --randomize --distinct-client-seed -d 32 --key-maximum=150000000 --key-minimum=1 --ratio=1:0 --key-pattern=P:P --show-config --cluster-mode 
   
3. What i am thinking could be, please check which part of change that i made
The happy flow should be aePostFunction makes the callback to processStorageToken, and eventually invokes complete_endWriteBatch
However, sometimes, occasionally, processStorageToken callback was not being invoked, neither the complete_endWriteBatch. And both keydb logs and memtier command just stuck there.  
We may suspect some locking things or maybe how writebatch used , may contribute to some complication which occasionally contributes to this threads hanging scenario. 
Really appreciate it if you can take a look at our implementation and see anything looks a bit suspcious. 
We have put a log entry in beginWriteBatch, processStorageToken, complete_endWriteBatch for tracking when the functions are executed. 

the following is subset of log since we log everytime when those functions are invoked and the whole log is huge. The problem is not consistent reproducible so we had to let the memtier run a bit while, eventually it stuck at beginwritebatch. 
![image](https://github.com/Snapchat/KeyDB/assets/15642771/e3ab3d96-9c74-42f4-a0d4-63a4f4d254d9)
[keydb-subset.log](https://github.com/Snapchat/KeyDB/files/13255067/keydb-subset.log)

@paulmchen @JohnSully

2023-11-03 22:42 UTC, paulmchen commented
@JohnSully Could you please check the issue mentioned in the previous message by @yzhao244?  We think the problem could be listed in 3, but we would like to hear your thoughts. Thank you.

2023-11-05 09:11 UTC, yzhao244 commented
@JohnSully Also, we would like to ask your opinion how to block clients in commitChanges. 
```
void redisDbPersistentData::commitChanges(const redisDbPersistentDataSnapshot **psnapshotFree)
{

    std::unordered_set<client *> setcBlocked; //How to block clients in commitChanges
    if (m_pdbSnapshotStorageFlush)
    {
        dictIterator *di = dictGetIterator(m_dictChangedStorageFlush);
        dictEntry *de;
        while ((de = dictNext(di)) != nullptr)
        {
            serializeAndStoreChange(m_spstorage.get(), (redisDbPersistentData*)m_pdbSnapshotStorageFlush, (const char*)dictGetKey(de), (bool)dictGetVal(de));
        }
        dictReleaseIterator(di);
        dictRelease(m_dictChangedStorageFlush);
        m_dictChangedStorageFlush = nullptr;
        *psnapshotFree = m_pdbSnapshotStorageFlush;
        m_pdbSnapshotStorageFlush = nullptr;
    }
    
    if (m_spstorage != nullptr)
    {
        auto *tok = m_spstorage->begin_endWriteBatch(serverTL->el, storageLoadCallback);
        if (tok != nullptr)
        {
            for (client *c : setcBlocked) //need to check how to push client to blocked list
            {
                if (!(c->flags & CLIENT_BLOCKED))
                    blockClient(c, BLOCKED_STORAGE);
            }
           // tok->setc = std::move(setcBlocked);
            tok->db = this;
            tok->type = StorageToken::TokenType::BatchWrite;
        }
    }
}
```

2023-11-08 20:19 UTC, JohnSully commented on src/db.cpp
> +           // tok->setc = std::move(setcBlocked);
remove commented out code

2023-11-08 20:21 UTC, JohnSully commented on src/db.cpp
> +            for (client *c : setcBlocked) //need to check how to push client to blocked list
Since this code doesn't work lets remove it.

2023-11-08 20:37 UTC, JohnSully requested changes

2023-11-08 20:37 UTC, JohnSully commented on src/db.cpp
> +        break;
Remove this case

2023-11-08 20:37 UTC, JohnSully commented on src/db.cpp
> +        break;
We should assert if we get here

2023-11-08 20:37 UTC, JohnSully commented on src/storage/rocksdb.cpp
> +    serverLog(LL_WARNING, "RocksDBStorageProvider::begin_endWriteBatch");
Remove debugging logs or set to LL_DEBUG

2023-11-08 20:37 UTC, JohnSully commented on src/storage/rocksdb.cpp
> +    serverLog(LL_WARNING, "RocksDBStorageProvider::complete_endWriteBatch");
remove

2023-11-10 15:58 UTC, yzhao244 commented
@JohnSully a quick update. Ankita has resolved code review comments. :)

2023-11-17 19:35 UTC, JohnSully approved these changes

2023-11-17 19:35 UTC, merged